blank_issues_enabled: false
contact_links:
  - name: Help and Support
    url: https://discord.gg/BWqgBg3
    about: EmuFlight Discord
  - name: Configurator software bugs
    url: https://github.com/emuflight/EmuConfigurator/issues
    about: Configurator software issues
