name: Feature Request
description: Suggest an idea for for a new feature for EmuFlight.
labels: ["Template: Feature Request"]
body:

  - type: markdown
    attributes:
      value: |
        **Please note that feature requests are not 'fire and forget'.**
        It is a lot more likely that the feature you would like to have will be implemented if you keep watching your feature request, and provide more details to developers looking into implementing your feature, and help them with testing.

  - type: textarea
    attributes:
      label: Is your feature request related to a problem? Please describe
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...].
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other information
      description: Add any other context or screenshots about the feature request that you think might be relevant here.
