on:
  push:
    tags:
    - '*'
  workflow_dispatch:
  repository_dispatch:
    types: [build]

name: "03 Build EmuFlight Full"

jobs:
  ci-gate:
    uses: ./.github/workflows/ci.yml

  build:
    needs: [ci-gate]
    continue-on-error: false
    timeout-minutes: 75
    strategy:
      fail-fast: false
      matrix:
        targets: [targets-group-1, targets-group-2, targets-group-3, targets-group-4, targets-group-5, targets-group-6, targets-group-7, targets-group-rest]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 9

    - uses: ./.github/actions/ef-toolchain

    - name: Get code version
      run: echo "VERSION=$(make version)" >> $GITHUB_ENV

    - name: Get revision tag
      if: startsWith(github.ref, 'refs/tags/')
      run: echo "REVISION_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

    - name: Make artifact name
      run: |
        if [[ "${{ github.repository }}" == "emuflight/EmuFlight" ]]; then
          echo "ARTIFACT_NAME=EmuFlight-${{ env.VERSION }}-${{ github.run_number }}" >> $GITHUB_ENV
        else
          echo "ARTIFACT_NAME=EmuFlight-${{ env.VERSION }}-${{ github.actor }}-${{ github.run_number }}" >> $GITHUB_ENV
        fi

    - name: Compile
      run: make ${{ matrix.targets }}

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ARTIFACT_NAME }}-${{ matrix.targets }}
        path: obj/*.hex
        overwrite: true
