on:
  push:
    tags:
    - '*'
    branches:
    - '*'
  pull_request:
    branches:
    - '*'
  repository_dispatch:
    types: [test]

name: "01 Test Suite"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    continue-on-error: false
    timeout-minutes: 30
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 9

    - uses: ./.github/actions/ef-toolchain
      with:
        python-version: '3.12'

    - name: Install BlocksRuntime
      run: sudo apt-get update && sudo apt-get install -y libblocksruntime-dev

    - name: Run tests
      run: make clean_test && make test
